### ISSUE TITLE
Featured Status Request Ghoulified Reality

### ISSUE THREAD

**Issue by Ghoulified** [wabbajack-tools/Requests-Reports#21]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

Ghoulified Reality

### Where do you offer support for your list ?

https://discord.gg/pU37zX4U

### Link to Readme / Documentation

https://themoddingbungalo.com/lists/ghoulified/index/

### Find A Modlist Assets and Meta Information

1 - https://github.com/Ghoulified/Ghoulified-Reality/blob/main/Ghoul_Logo_16x9.png
2 - Ghoulified Reality - Ghoulified
3 - https://ghoulified.netlify.app/
4 - Install Visual C++ x64 & .Net Runtime v5 desktop x64
5 - So my list matches best with Arkays Commandment but my list is very different in a multitude of ways graphics gameplay and philosophy. Arkay is punishing and doesn't hold back while my list isn't anywhere close to easy I chose mods that would help new players have a chance. I also include a lot of QOL mods that make 3bftweaks much more enjoyable plus a lot of community made mods.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://github.com/Ghoulified/Ghoulified-Reality/blob/main/Ghoul_Logo_16x9.webp

### When did you release the list on the Wabbajack UI?

Like 2 month's ago I think

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] My list has custom patching as required to address any known conflicts, bugs, or crashes
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by tr4wzified** [comment]
Hi, sorry for the late test. Sometimes that's what happens when you run on volunteers :)
I'll give this list a test tomorrow, it's installing now. Will get back to you.

**Comment by tr4wzified** [comment]
Hey, I had a look last night and played some more this morning. Nice and well-made list! I got a couple of small points though that need addressing before getting the modlist featured.

# Major issues
None!

# Minor issues - please fix before being featured
## Documentation & Wabbajack related
- Noticed a lot of dead Discord links in various places including your modlists.json, GitHub readme and NexusMods page. It'll be hard for people to find the support channels if they can't find where they're supposed to go.
- You should specify the modlist is permadeath by default in the documentation somewhere. It certainly surprised me when my test saves were suddenly all gone x) But much more troubling for the average user who may have just spent an hour creating a character only to die 10 minutes into the game having no idea what just happened.
- It should be more clear for AMD GPU users what to change before they can play your list. What ini setting exactly should be changed in the SkyrimPrefs ini? As far as I'm aware the DLAA mod automatically switches to FSR on AMD GPUs and the NVIDIA Reflex mod disables itself, but the comment in your readme is pretty confusing.

## List-related
- The vanilla start is available, which is very buggy. I played through it and it was fine for the most part, but the horses are going crazy once the beheading ceremony starts. Also important; It's practically impossible to actually play through it normally and get to the end on a hardcore list like this with the resources that are available.

# Nitpicks - personal recommendations & observations
## Documentation & Wabbajack related
- Modlists.json uses png image instead of webp. I would add this to the minor issues, but seeing as Wabbajack currently has a bug with webp images not loading on some machines it's fine to use png for now. I would add though that you please resize the image to 1920x1080 or smaller to lighten the performance load on the modlist gallery.
- I would add a small bit to the readme explaining what the NXM question is when they first start up Mod Organizer. It throws a lot of people off who have no idea what it is.
- Maybe a section about the optional mods in your readme would be nice? I don't think inexperienced users will notice these. The 21:9 support category is also quite hidden.
- I think it would be great if there was some more documentation on the list itself (aside from install instructions), maybe add some screenshots too? Or some additional explanations would be nice,  like what are those new UI symbols on the bottom left of the screen? Maybe point users to some of the more gameplay influencing mods of your list so they can read up a little while installing :)

## List-related
- Navigator-NavFixes.esl being overwritten by ITMs in some places by Falling Rocks Removed
- Lux causing some unresolved conflicts here and there. Anyway, nothing major in terms of conflict resolution as far as I saw.

**Comment by tr4wzified** [comment]
Please let me know once you got the issues sorted and I'll give it another go. Promise I'll get to it quickly, I'll keep the list installed for a bit :)

**Comment by tr4wzified** [comment]
Approved. Had some internal discussion and I was a bit too strict with the test according to our official criteria. Would still be awesome if you could pick up some of those points though :)
