### ISSUE TITLE
Featured Status Request The Nico Experience

### ISSUE THREAD

**Issue by therealnicoroshi** [wabbajack-tools/Requests-Reports#7]
### What game is your list for ?

TES Skyrim Special Edition

### What is your List Called ?

The Nico Expereince

### Where do you offer support for your list ?

https://discord.gg/kHehbzuFZ4

### Link to Readme / Documentation

https://github.com/therealnicoroshi/modlist/blob/main/README.md

### Find A Modlist Assets and Meta Information

1. ![](https://raw.githubusercontent.com/therealnicoroshi/modlist/main/NewCoverArtNE.jpg)
2. The Nico Experience | Nicoroshi
3. [Load order Library](https://loadorderlibrary.com/lists/the-nico-expereince)
4. List requires Skyrim AE 1.6.1170 with Paid AE upgrade Creation club content, and SE Creation kit from Steam
5. wizard results:
Skyrim SE/AE
I just want Skyrim (No sex)
Yes, but I want something other than vanilla
No LotDB
Yes I love Diablo

However this does not tell the full story of the Nico Experience since I don't think there is anything quite like it to compare to.

What it is NOT:
Not based on any major overhaul like Requiem. I have created my own.
Not 100% lore friendly but not completely fantasy either. A mix between them.

What you can expect:
Overhauled Movement with MCO combat, BowRapidCombo, Paraglider, Animated Traversal, and skill based animations.
Upgraded meshes and textures for just about everything with Parallax, and attention to matching/blending on items and the world around you.
More choices on character customization with presets, custom races, and many assets like hair, brows, eyes, and overlays.
A more immersive world with Immersive interactions, Dragonborn voice over, PC head tracking, sky Idles, Conditional Idles, Take a peek, Jayserpa's Quest expansions, wash that blood off,  and fully voiced followers.
More intuitive controls with Wheeler menu, Use or take/ read or take, Matter of time, and compass overhaul
New world spaces to explore outside of Tamriel with Wyrmstooth, Beyond Reach, Chanterelle, Darkend, The Shire and Forgotten City
New places to explore within Tamriel with Skyrim underground, Skyrim Sewers, and Forgotten Dungeons.
New creatures (some deleveled) from Mihail Monsters, 4th Unknown, Animallica, Immersive creatures, GoT/HoD/Diverse Dragons and Rogue like encounters
More challenging game play mechanics with Deadly dragons, Shadow of Skyrim, Static Skill leveling, Expereince, and Ordinator.
A world more alive with Immersive NPCs, Animated Boats and carriages, and populated Lands, roads, Paths.
A stable and fun play experience. I have literally played and evolved this list since Skyrim was released creating custom patches with SSEedit and the Creation Kit to fix conflicts, and mesh the mods I used together.
This is just scratching the surface of what The Nico Experience is but should give you an idea.

### Provide a WebP image for your modlist thumbnail for use in the "Find a List" tools and website promotion.

https://raw.githubusercontent.com/therealnicoroshi/modlist/main/Banner_NE.webP

### When did you release the list?

Jan 2024

### Agreements

- [X] The work submitted in this request is my own, and in my branding and doesn't infringe on existing Intelectual Property or Brands.
- [X] I agree to fully open, honest and possibly critical examination and discussion of my here submitted work.

**Comment by NotTotal** [comment]
Reject.
- No support history visible in discord. We cannot approve a list for featured if there is not 30 days of visible support for bugs/crashes/any other issue due to the modlist
- Readme is lacking. Please review the readmes for featured mod lists: [https://www.fgsmodlists.com/living-skyrim](Living Skyrim), [https://www.wabbajack.org/modlist/wj-featured/tempus_maledictum](Tempus), [https://www.wabbajack.org/modlist/Animonculory/ANVIL](Anvil), [https://www.wabbajack.org/modlist/Animonculory/dngg](DNGG), and [https://github.com/biggie-boss/LoreRim](LoreRim) for examples of the required information.
- Lacks sufficient patching regarding non-worldspace conflicts. Please run a check for conflicts in xedit and fix what needs to be fixed.

**Comment by therealnicoroshi** [comment]
1. No 30 days of bug reports because no bug reports submitted. 
The 2 posts that got removed was a person who was starting up python scripts for FNIS since they are part of MO2 and getting an error since my list uses Nemesis and NOT FNIS so NOT a bug. 
The other was an image from the CK (of which the one posted by the same user in general questions is still visable here)
https://steamuserimages-a.akamaihd.net/ugc/2520403568523603451/46C858E55485A2B85B83576B2F09008AD2DE563C/?imw=512&imh=320&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true
Again NOT a bug and posted in the wrong section so removed.

Readme is lacking?
Your links are broken please fix them so I can see what you mean. Broken links are Lacking in my opinion.

What is sufficient patching? Where is this lacking exactly? What is the criteria you are asking for?
If the game can play for 5-6 hours without a crash, freeze, or any issue through multiple world spaces, interior and exterior while producing the desired output exactly what sort of patching are you interested in or a better question is what sort do you feel is needed?
4 hour 47 min hour live stream from today with no issues:
https://www.youtube.com/live/euG2uvPbyYY?si=PJPc3E7Bl1QQxYjS
6 hour live stream with no issues:
https://www.youtube.com/live/PtKsDpWpKoI?si=Boh-xVmXn0RkDvdO

So.......All I can say is I am disappointed.

**Comment by NotTotal** [comment]
Here are the links again. 
- [[https://www.wabbajack.org/modlist/Animonculory/ANVIL](https://github.com/wabbajack-tools/Requests-Reports/issues/Anvil)]([https://www.wabbajack.org/modlist/Animonculory/ANVIL](https://github.com/wabbajack-tools/Requests-Reports/issues/Anvil))
- [https://www.wabbajack.org/modlist/wj-featured/tempus_maledictum](https://www.wabbajack.org/modlist/wj-featured/tempus_maledictum)
- [https://www.wabbajack.org/modlist/Animonculory/ANVIL](https://www.wabbajack.org/modlist/Animonculory/ANVIL)
- [https://github.com/biggie-boss/LoreRim](https://github.com/biggie-boss/LoreRim)
I suggest you review the readmes and compare them to yours. A user new to wabbajack would be unable to properly install wabbajack and your list by following your extremely bare bones instructions.

Without evidence of support for your list being provided we cannot approve a list for featured. Merely having evidence that you have provided install support is insufficient. I searched through your discord and was not able to see significant support being provided to address non-install related issues.

Further, featured modlist authors are expected to provide sufficient patching to address the conflicts present in their lists. From examining your list and patching it is clear that you have not made an effort to address conflicts other than those present in the worldspace or due to lighting. Again, I suggest running a check for conflicts and going through your entire list to fix the conflicts as necessary. We will not approve a list for featured that does not show signs of attempting to address conflicts. Relying on users to report bugs is insufficient. If you are unfamiliar with this process I suggest you review some of the guides that Lively has prepared at [https://github.com/LivelyDismay/Learn-To-Mod/wiki](https://github.com/LivelyDismay/Learn-To-Mod/wiki).

You are welcome to continue your list as unofficial for as long as you want. We will not grant it featured status until you address the issues that I have noted.

**Comment by therealnicoroshi** [comment]
Thank you for a more detailed description on 'why' it was rejected, and for Links that actually work for the readmes, and patching tutorial. 
It is MUCH more helpful to be given detailed reasons, and resources so that I can know where and how to address them if I choose to do so.

**Comment by therealnicoroshi** [comment]
NotTotal,
I have gotten permission to fork off BiggieBoss's LoreRim readme, and have updated mine accordingly.
I have gone through the mods in SSEedit and patched what I felt needed patching.
I cannot address the third requirement as I have not received any bug reports since I last posted here so I am unable to show the evidence you are requesting since it is out of my control.

I can understand if you still require said evidence of bug report support and will wait until I have some to fix and for the requested 30 days afterward if required.

When you have time please look at the readme and patching, and let me know if that is more like what is expected.

Thank you.
